name: Sonatto
description: "O catalogo de produtos da loja Sonatto."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "img/app-icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fontes/SourceCodePro-Italic-VariableFont_wght.ttf
        - asset: fontes/SourceCodePro-VariableFont_wght.ttf
        - asset: fontes/BowlbyOneSC-Regular.ttf
  assets:
  - img/
  - BD/
  - fontes/
